KPATH := $(HOME)/digilent/Linux-Digilent-Dev
ARCH := arm
CROSS_COMPILE := /opt/Xilinx/SDK/2016.2/gnu/arm/lin/bin/arm-xilinx-linux-gnueabi-

obj-m := ./src/ktimer.o

.PHONY: all clean doc

all:
	make -C $(KPATH) M=$(CURDIR) modules ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE)

clean:
	make -C $(KPATH) M=$(CURDIR) clean
	rm -rf ./doc

doc:
	doxygen ./Doxyfile
