KPATH := $(HOME)/raspberrypi/linux
TPATH := $(HOME)/raspberrypi/tools
ARCH := arm
CROSS_COMPILE := $(TPATH)/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-

obj-m := ./src/hrtimer.o

.PHONY: all clean doc

all:
	make -C $(KPATH) M=$(CURDIR) modules ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE)

clean:
	make -C $(KPATH) M=$(CURDIR) clean
	$(RM) ./doc

doc:
	doxygen ./Doxyfile
